config/routes.rb
Applicatiorails1::Application.routes.draw do
  
  resources :utilisateurs
  root :to => 'home#index'

end

app/models/utilisateur.rb
class Utilisateur < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
  
  def index
    @utilisateurs = Utilisateur.all
  end
  
  def show
    @utilisateur = Utilisateur.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= link_to 'liste utilisateurs', utilisateurs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Applicatiorails1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/utilisateurs/index.html.erb
<h1>Liste des utilisateurs</h1>

<table>
	<tr>
		<th>Nom</th>
		<th>Email</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	
	<% @utilisateurs.each do |utilisateur| %>
		<tr>
			<td><%= utilisateur.nom %></td>
			<td><%= utilisateur.email %></td>
			<td><%= link_to 'Montrer', utilisateur %></td>
			<td></td>
			<td></td>
		</tr>
	<% end %>
	
	
</table>

app/views/utilisateurs/show.html.erb
<%= @utilisateur.nom %> | <%= @utilisateur.email %>
<br /><br />
<%= link_to 'liste des utilisateurs', utilisateurs_path %>
